package com.example01.fusap.databindingreciclerview.entities;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example01.fusap.databindingreciclerview.entities.Champion;
import com.example01.fusap.databindingreciclerview.entities.ChampionStats;

import com.example01.fusap.databindingreciclerview.entities.ChampionDao;
import com.example01.fusap.databindingreciclerview.entities.ChampionStatsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig championDaoConfig;
    private final DaoConfig championStatsDaoConfig;

    private final ChampionDao championDao;
    private final ChampionStatsDao championStatsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        championDaoConfig = daoConfigMap.get(ChampionDao.class).clone();
        championDaoConfig.initIdentityScope(type);

        championStatsDaoConfig = daoConfigMap.get(ChampionStatsDao.class).clone();
        championStatsDaoConfig.initIdentityScope(type);

        championDao = new ChampionDao(championDaoConfig, this);
        championStatsDao = new ChampionStatsDao(championStatsDaoConfig, this);

        registerDao(Champion.class, championDao);
        registerDao(ChampionStats.class, championStatsDao);
    }
    
    public void clear() {
        championDaoConfig.getIdentityScope().clear();
        championStatsDaoConfig.getIdentityScope().clear();
    }

    public ChampionDao getChampionDao() {
        return championDao;
    }

    public ChampionStatsDao getChampionStatsDao() {
        return championStatsDao;
    }

}
