package com.example01.fusap.databindingreciclerview.entities;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example01.fusap.databindingreciclerview.entities.Champion;

import com.example01.fusap.databindingreciclerview.entities.ChampionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig championDaoConfig;

    private final ChampionDao championDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        championDaoConfig = daoConfigMap.get(ChampionDao.class).clone();
        championDaoConfig.initIdentityScope(type);

        championDao = new ChampionDao(championDaoConfig, this);

        registerDao(Champion.class, championDao);
    }
    
    public void clear() {
        championDaoConfig.getIdentityScope().clear();
    }

    public ChampionDao getChampionDao() {
        return championDao;
    }

}
